MAIN_MENU_OPTIONS = ["Head to Head comparison", "Team Analysis"]

MATCHES_COL = [
    "id",
    "season",
    "city",
    "date",
    "match_type",
    "player_of_match",
    "venue",
    "team1",
    "team2",
    "toss_winner",
    "toss_decision",
    "winner",
    "result",
    "result_margin",
    "target_runs",
    "target_overs",
    "super_over",
    "method",
    "umpire1",
    "umpire2",
]

PLAYERS_COL = [
    "match_id",
    "inning",
    "batting_team",
    "bowling_team",
    "over",
    "ball",
    "batter",
    "bowler",
    "non_striker",
    "batsman_runs",
    "extra_runs",
    "total_runs",
    "extras_type",
    "is_wicket",
    "player_dismissed",
    "dismissal_kind",
    "fielder",
]
